//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountNumberClient.localhost
{
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountNumberClient.localhost.IAccountNumberService")]
    public interface IAccountNumberService
    {
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountNumberService/Lookup", ReplyAction="http://tempuri.org/IAccountNumberService/LookupResponse")]
        string Lookup(string accountNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAccountNumberServiceChannel : AccountNumberClient.localhost.IAccountNumberService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AccountNumberServiceClient : System.ServiceModel.ClientBase<AccountNumberClient.localhost.IAccountNumberService>, AccountNumberClient.localhost.IAccountNumberService
    {
        
        public AccountNumberServiceClient()
        {
        }
        
        public AccountNumberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AccountNumberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AccountNumberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AccountNumberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string Lookup(string accountNumber)
        {
            return base.Channel.Lookup(accountNumber);
        }
    }
}
